repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        args: [--max-line-length=88]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
      - id: mypy
        name: mypy (fexapi)
        files: '^fexapi/.*\.py'
        exclude: ^(docs/|example-plugin/|tests/fixtures)
      - id: mypy
        name: mypy (fexservice)
        files: '^fexservice/.*\.py'
        exclude: ^(docs/|example-plugin/|tests/fixtures)
